version: "3.3"

services:
  api:
    image: planeat-auth
    container_name: planeat-auth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    depends_on:
      - db
    links:
      - db:postgres
    profiles:
      - prod
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/
    ports:
<<<<<<< HEAD:auth-service/docker-compose.yaml
      - "1337:5432"
=======
      - "${DB_EXTERNAL_PORT}:5432"
>>>>>>> d6ef7927f94ea8e2de5ba814c38d84b308e81320:stalevary-auth-service/docker-compose.yaml
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
<<<<<<< HEAD:auth-service/docker-compose.yaml
  db-data:



=======
  db-data:
>>>>>>> d6ef7927f94ea8e2de5ba814c38d84b308e81320:stalevary-auth-service/docker-compose.yaml
