version: "3.3"

services:
  api:
    image: planeat-auth
    container_name: planeat-auth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    depends_on:
      - db
    links:
      - db:postgres
    profiles:
      - prod
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "1337:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:
